In [1]:
import sys
import os
sys.path.append(os.pardir)

In [2]:
import pandas as pd
from datetime import datetime, timedelta

In [3]:
from extract import get_weather_client, fetch_weather, fetch_weather_batches

In [9]:
from extract import get_load_client, fetch_load

In [3]:
#two weeks
start_date = datetime(2025, 1, 1)
end_date = datetime(2025, 3, 1)

### Test weather pull

In [5]:
weather_client = get_weather_client()

In [5]:
weather_client

In [6]:
weather_df = fetch_weather(weather_client, start_date, end_date)

In [7]:
weather_df.head()

                           temperature
date
2025-01-01 00:00:00+00:00      -0.1385
2025-01-01 01:00:00+00:00      -0.1385
2025-01-01 02:00:00+00:00      -0.1385
2025-01-01 03:00:00+00:00      -0.3885
2025-01-01 04:00:00+00:00      -0.2885

In [8]:
weather_df.size

336

In [9]:
weatherbatch_df = fetch_weather_batches(weather_client, start_date, end_date)

Fetching weather 2025-01-01 to 2025-01-14...

In [10]:
load_client = get_load_client()

In [11]:
load_client

GridStatusClient(host=https://api.gridstatus.io/v1)

In [ ]:
load_df = fetch_load(load_client)

### Full Pull Test

In [4]:
from extract import fetch_all_data

In [5]:
df = fetch_all_data(start_date, end_date)

2026-06-06 14:55:24 - INFO - Fetching Page 1...
2026-06-06 14:55:24 - INFO - GET https://api.gridstatus.io/v1/datasets/spp_load_hourly/query
2026-06-06 14:55:24 - INFO - Params: {'start_time': Timestamp('2025-01-01 00:00:00'), 'end_time': Timestamp('2025-01-08 00:00:00'), 'publish_time_start': None, 'publish_time_end': None, 'limit': None, 'page': 1, 'page_size': None, 'resample_frequency': None, 'resample_by': None, 'resample_function': None, 'publish_time': None, 'timezone': None, 'cursor': '', 'filter_column': 'balancing_area_name', 'filter_value': 'SPP', 'filter_operator': '=', 'columns': 'interval_start_utc,balancing_area_name,control_zone_name,forecast_area_type,load', 'return_format': 'json', 'json_schema': 'array-of-arrays'}

Fetching 2025-01-01 to 2025-01-08...

2026-06-06 14:55:25 - INFO - Done in 1.04 seconds.
2026-06-06 14:55:25 - INFO - Total number of rows: 3024
2026-06-06 14:55:25 - INFO - Fetching Page 1...
2026-06-06 14:55:25 - INFO - GET https://api.gridstatus.io/v1/datasets/spp_load_hourly/query
2026-06-06 14:55:25 - INFO - Params: {'start_time': Timestamp('2025-01-08 00:00:00'), 'end_time': Timestamp('2025-01-15 00:00:00'), 'publish_time_start': None, 'publish_time_end': None, 'limit': None, 'page': 1, 'page_size': None, 'resample_frequency': None, 'resample_by': None, 'resample_function': None, 'publish_time': None, 'timezone': None, 'cursor': '', 'filter_column': 'balancing_area_name', 'filter_value': 'SPP', 'filter_operator': '=', 'columns': 'interval_start_utc,balancing_area_name,control_zone_name,forecast_area_type,load', 'return_format': 'json', 'json_schema': 'array-of-arrays'}
2026-06-06 14:55:25 - INFO - Too Many Requests. Limit: 1 per 1 second.. Retrying in 1 seconds. Retry 1 of 3.

Fetching 2025-01-08 to 2025-01-15...

2026-06-06 14:55:27 - INFO - Done in 1.62 seconds.
2026-06-06 14:55:27 - INFO - Total number of rows: 3024
2026-06-06 14:55:27 - INFO - Fetching Page 1...
2026-06-06 14:55:27 - INFO - GET https://api.gridstatus.io/v1/datasets/spp_load_hourly/query
2026-06-06 14:55:27 - INFO - Params: {'start_time': Timestamp('2025-01-15 00:00:00'), 'end_time': Timestamp('2025-01-22 00:00:00'), 'publish_time_start': None, 'publish_time_end': None, 'limit': None, 'page': 1, 'page_size': None, 'resample_frequency': None, 'resample_by': None, 'resample_function': None, 'publish_time': None, 'timezone': None, 'cursor': '', 'filter_column': 'balancing_area_name', 'filter_value': 'SPP', 'filter_operator': '=', 'columns': 'interval_start_utc,balancing_area_name,control_zone_name,forecast_area_type,load', 'return_format': 'json', 'json_schema': 'array-of-arrays'}
2026-06-06 14:55:27 - INFO - Too Many Requests. Limit: 1 per 1 second.. Retrying in 1 seconds. Retry 1 of 3.

Fetching 2025-01-15 to 2025-01-22...

2026-06-06 14:55:28 - INFO - Done in 1.48 seconds.
2026-06-06 14:55:28 - INFO - Total number of rows: 3024
2026-06-06 14:55:28 - INFO - Fetching Page 1...
2026-06-06 14:55:28 - INFO - GET https://api.gridstatus.io/v1/datasets/spp_load_hourly/query
2026-06-06 14:55:28 - INFO - Params: {'start_time': Timestamp('2025-01-22 00:00:00'), 'end_time': Timestamp('2025-01-29 00:00:00'), 'publish_time_start': None, 'publish_time_end': None, 'limit': None, 'page': 1, 'page_size': None, 'resample_frequency': None, 'resample_by': None, 'resample_function': None, 'publish_time': None, 'timezone': None, 'cursor': '', 'filter_column': 'balancing_area_name', 'filter_value': 'SPP', 'filter_operator': '=', 'columns': 'interval_start_utc,balancing_area_name,control_zone_name,forecast_area_type,load', 'return_format': 'json', 'json_schema': 'array-of-arrays'}

Fetching 2025-01-22 to 2025-01-29...

2026-06-06 14:55:29 - INFO - Too Many Requests. Limit: 1 per 1 second.. Retrying in 1 seconds. Retry 1 of 3.
2026-06-06 14:55:30 - INFO - Done in 1.65 seconds.
2026-06-06 14:55:30 - INFO - Total number of rows: 3010
2026-06-06 14:55:30 - INFO - Fetching Page 1...
2026-06-06 14:55:30 - INFO - GET https://api.gridstatus.io/v1/datasets/spp_load_hourly/query
2026-06-06 14:55:30 - INFO - Params: {'start_time': Timestamp('2025-01-29 00:00:00'), 'end_time': Timestamp('2025-02-05 00:00:00'), 'publish_time_start': None, 'publish_time_end': None, 'limit': None, 'page': 1, 'page_size': None, 'resample_frequency': None, 'resample_by': None, 'resample_function': None, 'publish_time': None, 'timezone': None, 'cursor': '', 'filter_column': 'balancing_area_name', 'filter_value': 'SPP', 'filter_operator': '=', 'columns': 'interval_start_utc,balancing_area_name,control_zone_name,forecast_area_type,load', 'return_format': 'json', 'json_schema': 'array-of-arrays'}
2026-06-06 14:55:30 - INFO - Too Many Requests. Limit: 1 per 1 second.. Retrying in 1 seconds. Retry 1 of 3.

Fetching 2025-01-29 to 2025-02-05...

2026-06-06 14:55:32 - INFO - Done in 1.48 seconds.
2026-06-06 14:55:32 - INFO - Total number of rows: 3024
2026-06-06 14:55:32 - INFO - Fetching Page 1...
2026-06-06 14:55:32 - INFO - GET https://api.gridstatus.io/v1/datasets/spp_load_hourly/query
2026-06-06 14:55:32 - INFO - Params: {'start_time': Timestamp('2025-02-05 00:00:00'), 'end_time': Timestamp('2025-02-12 00:00:00'), 'publish_time_start': None, 'publish_time_end': None, 'limit': None, 'page': 1, 'page_size': None, 'resample_frequency': None, 'resample_by': None, 'resample_function': None, 'publish_time': None, 'timezone': None, 'cursor': '', 'filter_column': 'balancing_area_name', 'filter_value': 'SPP', 'filter_operator': '=', 'columns': 'interval_start_utc,balancing_area_name,control_zone_name,forecast_area_type,load', 'return_format': 'json', 'json_schema': 'array-of-arrays'}

Fetching 2025-02-05 to 2025-02-12...

2026-06-06 14:55:32 - INFO - Too Many Requests. Limit: 1 per 1 second.. Retrying in 1 seconds. Retry 1 of 3.
2026-06-06 14:55:33 - INFO - Done in 1.53 seconds.
2026-06-06 14:55:33 - INFO - Total number of rows: 3024
2026-06-06 14:55:33 - INFO - Fetching Page 1...
2026-06-06 14:55:33 - INFO - GET https://api.gridstatus.io/v1/datasets/spp_load_hourly/query
2026-06-06 14:55:33 - INFO - Params: {'start_time': Timestamp('2025-02-12 00:00:00'), 'end_time': Timestamp('2025-02-19 00:00:00'), 'publish_time_start': None, 'publish_time_end': None, 'limit': None, 'page': 1, 'page_size': None, 'resample_frequency': None, 'resample_by': None, 'resample_function': None, 'publish_time': None, 'timezone': None, 'cursor': '', 'filter_column': 'balancing_area_name', 'filter_value': 'SPP', 'filter_operator': '=', 'columns': 'interval_start_utc,balancing_area_name,control_zone_name,forecast_area_type,load', 'return_format': 'json', 'json_schema': 'array-of-arrays'}

Fetching 2025-02-12 to 2025-02-19...

2026-06-06 14:55:33 - INFO - Too Many Requests. Limit: 1 per 1 second.. Retrying in 1 seconds. Retry 1 of 3.
2026-06-06 14:55:35 - INFO - Done in 1.8 seconds.
2026-06-06 14:55:35 - INFO - Total number of rows: 3024
2026-06-06 14:55:35 - INFO - Fetching Page 1...
2026-06-06 14:55:35 - INFO - GET https://api.gridstatus.io/v1/datasets/spp_load_hourly/query
2026-06-06 14:55:35 - INFO - Params: {'start_time': Timestamp('2025-02-19 00:00:00'), 'end_time': Timestamp('2025-02-26 00:00:00'), 'publish_time_start': None, 'publish_time_end': None, 'limit': None, 'page': 1, 'page_size': None, 'resample_frequency': None, 'resample_by': None, 'resample_function': None, 'publish_time': None, 'timezone': None, 'cursor': '', 'filter_column': 'balancing_area_name', 'filter_value': 'SPP', 'filter_operator': '=', 'columns': 'interval_start_utc,balancing_area_name,control_zone_name,forecast_area_type,load', 'return_format': 'json', 'json_schema': 'array-of-arrays'}

Fetching 2025-02-19 to 2025-02-26...

2026-06-06 14:55:35 - INFO - Too Many Requests. Limit: 1 per 1 second.. Retrying in 1 seconds. Retry 1 of 3.
2026-06-06 14:55:36 - INFO - Done in 1.56 seconds.
2026-06-06 14:55:36 - INFO - Total number of rows: 3024
2026-06-06 14:55:36 - INFO - Fetching Page 1...
2026-06-06 14:55:36 - INFO - GET https://api.gridstatus.io/v1/datasets/spp_load_hourly/query
2026-06-06 14:55:36 - INFO - Params: {'start_time': Timestamp('2025-02-26 00:00:00'), 'end_time': Timestamp('2025-03-01 00:00:00'), 'publish_time_start': None, 'publish_time_end': None, 'limit': None, 'page': 1, 'page_size': None, 'resample_frequency': None, 'resample_by': None, 'resample_function': None, 'publish_time': None, 'timezone': None, 'cursor': '', 'filter_column': 'balancing_area_name', 'filter_value': 'SPP', 'filter_operator': '=', 'columns': 'interval_start_utc,balancing_area_name,control_zone_name,forecast_area_type,load', 'return_format': 'json', 'json_schema': 'array-of-arrays'}
2026-06-06 14:55:37 - INFO - Too Many Requests. Limit: 1 per 1 second.. Retrying in 1 seconds. Retry 1 of 3.

Fetching 2025-02-26 to 2025-03-01...

2026-06-06 14:55:38 - INFO - Done in 1.51 seconds.
2026-06-06 14:55:38 - INFO - Total number of rows: 1296

Fetching weather 2025-01-01 to 2025-01-31...
Fetching weather 2025-01-31 to 2025-03-01...

In [6]:
df.head()

                                load  temperature
date
2025-01-01 00:00:00+00:00  67730.086      -0.1385
2025-01-01 01:00:00+00:00  66692.826      -0.1385
2025-01-01 02:00:00+00:00  65610.642      -0.1385
2025-01-01 03:00:00+00:00  64622.860      -0.3885
2025-01-01 04:00:00+00:00  63448.364      -0.2885