In [1]:
import sys
import os
sys.path.append(os.pardir)

In [2]:
import pandas as pd
from datetime import datetime, timedelta

In [3]:
from extract import get_weather_client, fetch_weather, fetch_weather_batches

In [5]:
from extract import get_load_client, fetch_load

ModuleNotFoundError: No module named 'openmeteo_requests'

In [3]:
#six months
#year, month, day
start_date = datetime(2024, 1, 1)
end_date = datetime(2024, 1, 4)

In [4]:
load_client = get_load_client()

NameError: name 'get_load_client' is not defined

### Test weather pull

In [5]:
weather_client = get_weather_client()

In [5]:
weather_client

In [6]:
weather_df = fetch_weather(weather_client, start_date, end_date)

In [7]:
weather_df.head()

                           temperature
date
2025-01-01 00:00:00+00:00      -0.1385
2025-01-01 01:00:00+00:00      -0.1385
2025-01-01 02:00:00+00:00      -0.1385
2025-01-01 03:00:00+00:00      -0.3885
2025-01-01 04:00:00+00:00      -0.2885

In [8]:
weather_df.size

336

In [9]:
weatherbatch_df = fetch_weather_batches(weather_client, start_date, end_date)

Fetching weather 2025-01-01 to 2025-01-14...

In [10]:
load_client = get_load_client()

In [11]:
load_client

GridStatusClient(host=https://api.gridstatus.io/v1)

In [ ]:
load_df = fetch_load(load_client)

### Full Pull Test

In [4]:
from extract import fetch_all_data

In [ ]:
df = fetch_all_data(start_date, end_date)

In [6]:
df.head()

                                load  temperature
date
2025-01-01 00:00:00+00:00  67730.086      -0.1385
2025-01-01 01:00:00+00:00  66692.826      -0.1385
2025-01-01 02:00:00+00:00  65610.642      -0.1385
2025-01-01 03:00:00+00:00  64622.860      -0.3885
2025-01-01 04:00:00+00:00  63448.364      -0.2885

## Testing EIA hourly load pull

In [4]:
from extract import fetch_EIA_load, clean_EIA_load

In [5]:
df = fetch_EIA_load(start_date, end_date)

  load 2025-01-01 to 2025-01-31: starting...
  load 2025-01-01 to 2025-01-31: fetched 744 / 744 rows
  load 2025-01-01 to 2025-01-31: complete
  load 2025-02-01 to 2025-03-03: starting...
  load 2025-02-01 to 2025-03-03: fetched 744 / 744 rows
  load 2025-02-01 to 2025-03-03: complete
  load 2025-03-04 to 2025-04-03: starting...
  load 2025-03-04 to 2025-04-03: fetched 744 / 744 rows
  load 2025-03-04 to 2025-04-03: complete
  load 2025-04-04 to 2025-05-04: starting...
  load 2025-04-04 to 2025-05-04: fetched 744 / 744 rows
  load 2025-04-04 to 2025-05-04: complete
  load 2025-05-05 to 2025-06-04: starting...
  load 2025-05-05 to 2025-06-04: fetched 744 / 744 rows
  load 2025-05-05 to 2025-06-04: complete
  load 2025-06-05 to 2025-07-01: starting...
  load 2025-06-05 to 2025-07-01: fetched 648 / 648 rows
  load 2025-06-05 to 2025-07-01: complete

In [10]:
df[df.duplicated()]

Empty DataFrame
Columns: [period, respondent, respondent-name, type, type-name, value, value-units]
Index: []

In [6]:
df.head()

,period,respondent,respondent-name,type,type-name,value,value-units
0,2025-01-01T00,SWPP,Southwest Power Pool,D,Demand,33978,megawatthours
1,2025-01-01T01,SWPP,Southwest Power Pool,D,Demand,34048,megawatthours
2,2025-01-01T02,SWPP,Southwest Power Pool,D,Demand,33484,megawatthours
3,2025-01-01T03,SWPP,Southwest Power Pool,D,Demand,32983,megawatthours
4,2025-01-01T04,SWPP,Southwest Power Pool,D,Demand,32449,megawatthours

In [ ]:
df.head(60)

In [ ]:
df.loc[730:760]

In [6]:
df[df.duplicated(subset = ["period"])]

Empty DataFrame
Columns: [period, respondent, respondent-name, type, type-name, value, value-units]
Index: []

In [19]:
#batching reppeast the first day of the last batch

In [7]:
clean_load = clean_EIA_load(df)

In [11]:
def clean_load(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()
    df["period"] = pd.to_datetime(df["period"], format="%Y-%m-%dT%H", utc=True)
    df = df.set_index("period")
    df.index.name = "date"
    #df.index.freq = "h"
    return df

In [12]:
clean_df = clean_load(df)

In [ ]:
clean_df.head(60)

In [15]:
clean_df.index

DatetimeIndex(['2025-01-01 00:00:00+00:00', '2025-01-01 01:00:00+00:00',
               '2025-01-01 02:00:00+00:00', '2025-01-01 03:00:00+00:00',
               '2025-01-01 04:00:00+00:00', '2025-01-01 05:00:00+00:00',
               '2025-01-01 06:00:00+00:00', '2025-01-01 07:00:00+00:00',
               '2025-01-01 08:00:00+00:00', '2025-01-01 09:00:00+00:00',
               ...
               '2025-03-01 14:00:00+00:00', '2025-03-01 15:00:00+00:00',
               '2025-03-01 16:00:00+00:00', '2025-03-01 17:00:00+00:00',
               '2025-03-01 18:00:00+00:00', '2025-03-01 19:00:00+00:00',
               '2025-03-01 20:00:00+00:00', '2025-03-01 21:00:00+00:00',
               '2025-03-01 22:00:00+00:00', '2025-03-01 23:00:00+00:00'],
              dtype='datetime64[us, UTC]', name='date', length=1464, freq=None)

In [8]:
clean_load.head()

,respondent,respondent-name,type,type-name,value,value-units
date,,,,,,
2025-01-01 00:00:00+00:00,SWPP,Southwest Power Pool,D,Demand,33978,megawatthours
2025-01-01 01:00:00+00:00,SWPP,Southwest Power Pool,D,Demand,34048,megawatthours
2025-01-01 02:00:00+00:00,SWPP,Southwest Power Pool,D,Demand,33484,megawatthours
2025-01-01 03:00:00+00:00,SWPP,Southwest Power Pool,D,Demand,32983,megawatthours
2025-01-01 04:00:00+00:00,SWPP,Southwest Power Pool,D,Demand,32449,megawatthours

In [9]:
clean_load.index

DatetimeIndex(['2025-01-01 00:00:00+00:00', '2025-01-01 01:00:00+00:00',
               '2025-01-01 02:00:00+00:00', '2025-01-01 03:00:00+00:00',
               '2025-01-01 04:00:00+00:00', '2025-01-01 05:00:00+00:00',
               '2025-01-01 06:00:00+00:00', '2025-01-01 07:00:00+00:00',
               '2025-01-01 08:00:00+00:00', '2025-01-01 09:00:00+00:00',
               ...
               '2025-03-01 14:00:00+00:00', '2025-03-01 15:00:00+00:00',
               '2025-03-01 16:00:00+00:00', '2025-03-01 17:00:00+00:00',
               '2025-03-01 18:00:00+00:00', '2025-03-01 19:00:00+00:00',
               '2025-03-01 20:00:00+00:00', '2025-03-01 21:00:00+00:00',
               '2025-03-01 22:00:00+00:00', '2025-03-01 23:00:00+00:00'],
              dtype='datetime64[us, UTC]', name='date', length=1440, freq='h')

In [11]:
clean_load[["value"]]

                           value
date
2025-01-01 00:00:00+00:00  33978
2025-01-01 01:00:00+00:00  34048
2025-01-01 02:00:00+00:00  33484
2025-01-01 03:00:00+00:00  32983
2025-01-01 04:00:00+00:00  32449
...                          ...
2025-03-01 19:00:00+00:00  29484
2025-03-01 20:00:00+00:00  29064
2025-03-01 21:00:00+00:00  28774
2025-03-01 22:00:00+00:00  28731
2025-03-01 23:00:00+00:00  29059

[1440 rows x 1 columns]

In [11]:
#test the weather and is day extract 
from extract import get_weather_client, fetch_weather_batches

In [12]:
client = get_weather_client()

In [14]:
weather = fetch_weather_batches(client, start_date, end_date)

Fetching weather 2025-01-01 to 2025-01-31...
Fetching weather 2025-01-31 to 2025-03-02...
Fetching weather 2025-03-02 to 2025-04-01...
Fetching weather 2025-04-01 to 2025-05-01...
Fetching weather 2025-05-01 to 2025-05-31...
Fetching weather 2025-05-31 to 2025-06-30...
Fetching weather 2025-06-30 to 2025-07-01...

In [23]:
weather[weather.index.duplicated()]

                           temperature  is_day
date
2025-01-31 00:00:00+00:00     7.361500     0.0
2025-01-31 01:00:00+00:00     6.461500     0.0
2025-01-31 02:00:00+00:00     6.661500     0.0
2025-01-31 03:00:00+00:00     6.361500     0.0
2025-01-31 04:00:00+00:00     6.111500     0.0
...                                ...     ...
2025-06-30 19:00:00+00:00    24.911501     1.0
2025-06-30 20:00:00+00:00    24.811501     1.0
2025-06-30 21:00:00+00:00    22.311501     1.0
2025-06-30 22:00:00+00:00    23.361500     1.0
2025-06-30 23:00:00+00:00    25.161501     1.0

[144 rows x 2 columns]